import { Navigate, useRoutes } from "react-router-dom";
import { PATHS } from "./paths";
import * as Elements from "./elements";

export default function Router() {
  return useRoutes([
    { path: PATHS.home, element: <Elements.Home /> },
    { path: PATHS.about, element: <Elements.About /> },
    { path: PATHS.products, element: <Elements.Products /> },
    { path: PATHS.requestQuote, element: <Elements.RequestQuote /> },
    { path: PATHS.careers, element: <Elements.Careers /> },
    { path: PATHS.privacyPolicy, element: <Elements.PrivacyPolicy /> },
    { path: PATHS.termsConditions, element: <Elements.TermsConditions /> },
    { path: PATHS.contactUs, element: <Elements.Contact /> },
    { path: PATHS.stockManagement, element: <Elements.IgxStock /> },
    { path: PATHS.odooErp, element: <Elements.OdooErp /> },
    { path: PATHS.retailPos, element: <Elements.RetailPos /> },
    { path: PATHS.customerRelation, element: <Elements.CustomerRelation /> },
    { path: PATHS.caseStudies, element: <Elements.CaseStudies /> },
    { path: PATHS.getInTouch, element: <Elements.GetinTouchNew /> },
    { path: PATHS.globalLocations, element: <Elements.GlobalLocations /> },
    { path: PATHS.portfolio, element: <Elements.Portfolio /> },
    { path: PATHS.implementationIntegration, element: <Elements.ImplementationIntegration /> },
    { path: PATHS.managedServices, element: <Elements.ManagedServices /> },
    { path: PATHS.consultingAdvisory, element: <Elements.ConsultingAdvisory /> },
    { path: PATHS.supportOptimization, element: <Elements.SupportOptimization /> },
    { path: PATHS.digitalMarketing, element: <Elements.DigitalMarketing /> },
    { path: PATHS.microsoft, element: <Elements.MicrosoftSolution /> },
    { path: PATHS.zoho, element: <Elements.ZohoSolution /> },
    { path: PATHS.odoo, element: <Elements.OdooSolution /> },
    { path: PATHS.shopify, element: <Elements.ShopifySolution /> },
    { path: PATHS.apiIntegration, element: <Elements.ApiIntegration /> },
    { path: PATHS.dataAnalyticsAi, element: <Elements.DataAnalyticsAI /> },
    { path: PATHS.digitalTransformation, element: <Elements.DigitalTransformation /> },
    { path: PATHS.intelligentAutomation, element: <Elements.IntelligentAutomation /> },
    { path: PATHS.modernApplications, element: <Elements.ModernApplication /> },
    { path: PATHS.webDevelopment, element: <Elements.Webdev /> },
    { path: PATHS.mobileAppDevelopment, element: <Elements.MobileAppDevelopment /> },
    { path: PATHS.artificialIntelligence, element: <Elements.ArtificialIntelligence /> },
    { path: PATHS.cloudComputing, element: <Elements.CloudComputing /> },
    { path: PATHS.dataEngineering, element: <Elements.DataEngineering /> },
    { path: PATHS.healthcare, element: <Elements.Healthcare /> },
    { path: PATHS.finance, element: <Elements.Finance /> },
    { path: PATHS.retail, element: <Elements.Retail /> },
    { path: PATHS.ecommerce, element: <Elements.ECommerce /> },
    { path: PATHS.manufacturing, element: <Elements.Manufacturing /> },
    { path: PATHS.transport, element: <Elements.Transport /> },
    // Redirects/Legacy
    { path: PATHS.implementationLegacy, element: <Navigate to={PATHS.implementationIntegration} replace /> },
    { path: PATHS.managedLegacy, element: <Navigate to={PATHS.managedServices} replace /> },
    { path: PATHS.consultingLegacy, element: <Navigate to={PATHS.consultingAdvisory} replace /> },
    { path: PATHS.supportLegacy, element: <Navigate to={PATHS.supportOptimization} replace /> },
    { path: PATHS.digitalMarketingLegacy, element: <Navigate to={PATHS.digitalMarketing} replace /> },
    { path: PATHS.aboutUsLegacy, element: <Navigate to={PATHS.about} replace /> },
    { path: PATHS.cloudComputingLegacy, element: <Navigate to={PATHS.cloudComputing} replace /> },
    { path: PATHS.webAppDevelopmentLegacy, element: <Navigate to={PATHS.modernApplications} replace /> },
    { path: PATHS.websiteDevelopmentLegacy, element: <Navigate to={PATHS.webDevelopment} replace /> },
    
    { path: PATHS.microsoftLegacy, element: <Elements.MicrosoftSolution /> },
    { path: PATHS.zohoLegacy, element: <Elements.ZohoSolution /> },
    { path: PATHS.odooLegacy, element: <Elements.OdooSolution /> },
    { path: PATHS.shopifyLegacy, element: <Elements.ShopifySolution /> },
    { path: PATHS.healthcareLegacy, element: <Elements.Healthcare /> },
    { path: PATHS.retailLegacy, element: <Elements.Retail /> },
    { path: PATHS.manufacturingLegacy, element: <Elements.Manufacturing /> },
    { path: PATHS.ecommerceLegacy, element: <Elements.ECommerce /> },
    { path: PATHS.financeLegacy, element: <Elements.Finance /> },
    // Catch-all
    { path: "*", element: <Navigate to={PATHS.home} replace /> },
  ]);
}
